### ISSUE TITLE
Name precedence parameter spelling

### ISSUE THREAD

**Issue by nbachm** [glueckkanja-gab/terraform-provider-aztools#9]
### Terraform Version
v0.14.10
source = "glueckkanja-gab/aztools",  version = "0.0.4-pre"

### Affected Resource(s)
General issue, affecting all resources of this provider.

### Description
In the resource "aztools_resource_name", the parameter for precedence is spelled name_precendence (there is a "n" too much in prece**n**dence)
Reference: https://registry.terraform.io/providers/glueckkanja-gab/aztools/latest/docs/resources/azfoundation_resource_name 

In the schema.naming.json, the parameter is spelled namePrecedence
Reference: https://registry.terraform.io/providers/glueckkanja-gab/aztools/latest/docs#example-schemanamingjson 

Is there a chance to align both parameter names, in terms of the spelling and maybe also in terms of the underscore?

Thanks!

**Comment by petr-stupka** [comment]
* misspelling fixed
* difference in underscores is based on json and hcl language format. this will be not changed for now.
